import { GridColumns } from "@mui/x-data-grid";

export const columns: GridColumns = [
  {
    field: "광고채널",
    headerName: "광고채널",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "캠페인",
    headerName: "캠페인",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "광고세트",
    headerName: "광고세트",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "광고",
    headerName: "광고",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "이미지",
    headerName: "이미지",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "제품명",
    headerName: "제품명",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "광고비",
    headerName: "광고비",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "전환수",
    headerName: "전환수",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "전환값",
    headerName: "전환값",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "CPM",
    headerName: "CPM",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "CTR",
    headerName: "CTR",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "CPC",
    headerName: "CPC",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "CPA",
    headerName: "CPA",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "ROAS",
    headerName: "ROAS",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "ad_id",
    headerName: "ad_id",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "ad_group_id",
    headerName: "ad_group_id",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
];

export const rows = [
  {
    id: 1,
    광고채널: "NAVER_SA",
    캠페인: "demo_조세준_5_전환",
    광고세트: "demo_조세준_5_전환_소구포인트_3",
    광고: "조세준_화사한 재생크림 50ml_NAVER_SA_1",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "12,877원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id: "demo_카페24화사한_화사한 재생크림 50ml_NAVER_SA_14_1",
    ad_group_id: "demo_조세준_5_전환_소구포인트_3",
  },
  {
    id: 2,
    광고채널: "NAVER_GFA",
    캠페인: "demo_설주윤_5_전환",
    광고세트: "demo_설주윤_5_전환_소구포인트_3",
    광고: "설주윤_화사한 수분크림 50ml 속건성 크림_NAVER_GFA_2",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "12,756원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id: "demo_스마트스토어_화사한 수분크림 50ml 속건성 크림_NAVER_GFA_17_2",
    ad_group_id: "demo_설주윤_5_전환_소구포인트_3",
  },
  {
    id: 3,
    광고채널: "NAVER_GFA",
    캠페인: "demo_김준석_5_전환",
    광고세트: "demo_김준석_5_전환_소구포인트_3",
    광고: "김준석_화사한 촉촉한팩 5pack_NAVER_GFA_3",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "12,599원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id: "demo_카페24화사한_화사한 촉촉한팩 5pack_NAVER_GFA_17_3",
    ad_group_id: "demo_김준석_5_전환_소구포인트_3",
  },
  {
    id: 4,
    광고채널: "FACEBOOK",
    캠페인: "demo_설주윤_5_전환",
    광고세트: "demo_설주윤_5_전환_소구포인트_3",
    광고: "설주윤_화사한 아이크림 15ml 눈가주름 탄력 크림, 1개_FACEBOOK_3",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "12,550원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id:
      "demo_쿠팡_화사한 아이크림 15ml 눈가주름 탄력 크림, 1개_FACEBOOK_16_3",
    ad_group_id: "demo_설주윤_5_전환_소구포인트_3",
  },
  {
    id: 5,
    광고채널: "NAVER_GFA",
    캠페인: "demo_설주윤_5_전환",
    광고세트: "demo_설주윤_5_전환_소구포인트_1",
    광고: "설주윤_화사한 아이크림 15ml 눈가주름 탄력 크림, 1개_NAVER_GFA_3",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "12,550원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id:
      "demo_쿠팡_화사한 아이크림 15ml 눈가주름 탄력 크림, 1개_NAVER_GFA_17_3",
    ad_group_id: "demo_설주윤_5_전환_소구포인트_1",
  },
  {
    id: 6,
    광고채널: "KAKAOMOMENT",
    캠페인: "demo_조세준_5_전환",
    광고세트: "demo_조세준_5_전환_소구포인트_2",
    광고: "조세준_화사한 재생크림 50ml 미백 재생 크림, 1개_KAKAOMOMENT_3",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "12,150원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id:
      "demo_쿠팡_화사한 재생크림 50ml 미백 재생 크림, 1개_KAKAOMOMENT_18_3",
    ad_group_id: "demo_조세준_5_전환_소구포인트_2",
  },
  {
    id: 7,
    광고채널: "NAVER_SA",
    캠페인: "demo_설주윤_5_전환",
    광고세트: "demo_설주윤_5_전환_소구포인트_2",
    광고: "설주윤_화사한 아이크림 15ml 눈가주름 탄력 크림, 1개_NAVER_SA_1",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "12,150원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id:
      "demo_쿠팡_화사한 아이크림 15ml 눈가주름 탄력 크림, 1개_NAVER_SA_14_1",
    ad_group_id: "demo_설주윤_5_전환_소구포인트_2",
  },
  {
    id: 8,
    광고채널: "NAVER_GFA",
    캠페인: "demo_조세준_5_전환",
    광고세트: "demo_조세준_5_전환_소구포인트_3",
    광고: "조세준_화사한 재생크림 50ml_NAVER_GFA_2",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "12,034원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id: "demo_카페24화사한_화사한 재생크림 50ml_NAVER_GFA_17_2",
    ad_group_id: "demo_조세준_5_전환_소구포인트_3",
  },
  {
    id: 9,
    광고채널: "FACEBOOK",
    캠페인: "demo_설주윤_5_전환",
    광고세트: "demo_설주윤_5_전환_소구포인트_2",
    광고: "설주윤_화사한 아이크림 15ml 눈가주름 탄력 크림_FACEBOOK_2",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "12,034원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id:
      "demo_스마트스토어_화사한 아이크림 15ml 눈가주름 탄력 크림_FACEBOOK_16_2",
    ad_group_id: "demo_설주윤_5_전환_소구포인트_2",
  },
  {
    id: 10,
    광고채널: "KAKAOMOMENT",
    캠페인: "demo_설주윤_5_전환",
    광고세트: "demo_설주윤_5_전환_소구포인트_3",
    광고: "설주윤_화사한 수분크림 50ml 속건성 크림_KAKAOMOMENT_3",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "12,034원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id:
      "demo_스마트스토어_화사한 수분크림 50ml 속건성 크림_KAKAOMOMENT_18_3",
    ad_group_id: "demo_설주윤_5_전환_소구포인트_3",
  },
  {
    id: 11,
    광고채널: "FACEBOOK",
    캠페인: "demo_조세준_5_전환",
    광고세트: "demo_조세준_5_전환_소구포인트_2",
    광고: "조세준_화사한 재생크림 50ml 미백 재생 크림, 1개_FACEBOOK_2",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "12,016원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id: "demo_쿠팡_화사한 재생크림 50ml 미백 재생 크림, 1개_FACEBOOK_16_2",
    ad_group_id: "demo_조세준_5_전환_소구포인트_2",
  },
  {
    id: 12,
    광고채널: "GOOGLE_ADS",
    캠페인: "demo_설주윤_5_전환",
    광고세트: "demo_설주윤_5_전환_소구포인트_3",
    광고: "설주윤_화사한 아이크림 15ml 눈가주름 탄력 크림_GOOGLE_ADS_3",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "11,914원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id:
      "demo_스마트스토어_화사한 아이크림 15ml 눈가주름 탄력 크림_GOOGLE_ADS_15_3",
    ad_group_id: "demo_설주윤_5_전환_소구포인트_3",
  },
  {
    id: 13,
    광고채널: "NAVER_SA",
    캠페인: "demo_설주윤_5_전환",
    광고세트: "demo_설주윤_5_전환_소구포인트_1",
    광고: "설주윤_화사한 아이크림 15ml 눈가주름 탄력 크림, 1개_NAVER_SA_2",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "11,883원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id:
      "demo_쿠팡_화사한 아이크림 15ml 눈가주름 탄력 크림, 1개_NAVER_SA_14_2",
    ad_group_id: "demo_설주윤_5_전환_소구포인트_1",
  },
  {
    id: 14,
    광고채널: "FACEBOOK",
    캠페인: "demo_조세준_5_전환",
    광고세트: "demo_조세준_5_전환_소구포인트_2",
    광고: "조세준_화사한 재생크림 50ml 미백 재생 크림, 1개_FACEBOOK_3",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "11,883원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id: "demo_쿠팡_화사한 재생크림 50ml 미백 재생 크림, 1개_FACEBOOK_16_3",
    ad_group_id: "demo_조세준_5_전환_소구포인트_2",
  },
  {
    id: 15,
    광고채널: "FACEBOOK",
    캠페인: "demo_설주윤_5_전환",
    광고세트: "demo_설주윤_5_전환_소구포인트_1",
    광고: "설주윤_화사한 수분크림 50ml 속건성 크림_FACEBOOK_2",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "11,794원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id: "demo_스마트스토어_화사한 수분크림 50ml 속건성 크림_FACEBOOK_16_2",
    ad_group_id: "demo_설주윤_5_전환_소구포인트_1",
  },
  {
    id: 16,
    광고채널: "NAVER_GFA",
    캠페인: "demo_설주윤_5_전환",
    광고세트: "demo_설주윤_5_전환_소구포인트_1",
    광고: "설주윤_화사한 수분크림 50ml 속건성 크림_NAVER_GFA_3",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "11,794원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id: "demo_스마트스토어_화사한 수분크림 50ml 속건성 크림_NAVER_GFA_17_3",
    ad_group_id: "demo_설주윤_5_전환_소구포인트_1",
  },
  {
    id: 17,
    광고채널: "FACEBOOK",
    캠페인: "demo_조세준_5_전환",
    광고세트: "demo_조세준_5_전환_소구포인트_1",
    광고: "조세준_화사한 재생크림 50ml 미백 재생 크림, 1개_FACEBOOK_3",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "11,749원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id: "demo_쿠팡_화사한 재생크림 50ml 미백 재생 크림, 1개_FACEBOOK_16_3",
    ad_group_id: "demo_조세준_5_전환_소구포인트_1",
  },
  {
    id: 18,
    광고채널: "NAVER_GFA",
    캠페인: "demo_설주윤_5_전환",
    광고세트: "demo_설주윤_5_전환_소구포인트_3",
    광고: "설주윤_화사한 수분크림 50ml 속건성 크림_NAVER_GFA_3",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "11,553원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id: "demo_스마트스토어_화사한 수분크림 50ml 속건성 크림_NAVER_GFA_17_3",
    ad_group_id: "demo_설주윤_5_전환_소구포인트_3",
  },
  {
    id: 19,
    광고채널: "NAVER_SA",
    캠페인: "demo_조세준_5_전환",
    광고세트: "demo_조세준_5_전환_소구포인트_1",
    광고: "조세준_화사한 재생크림 50ml 미백 재생 크림, 1개_NAVER_SA_1",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "11,482원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id: "demo_쿠팡_화사한 재생크림 50ml 미백 재생 크림, 1개_NAVER_SA_14_1",
    ad_group_id: "demo_조세준_5_전환_소구포인트_1",
  },
  {
    id: 20,
    광고채널: "GOOGLE_ADS",
    캠페인: "demo_조세준_5_전환",
    광고세트: "demo_조세준_5_전환_소구포인트_1",
    광고: "조세준_화사한 재생크림 50ml 미백 재생 크림_GOOGLE_ADS_2",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "11,432원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id:
      "demo_스마트스토어_화사한 재생크림 50ml 미백 재생 크림_GOOGLE_ADS_15_2",
    ad_group_id: "demo_조세준_5_전환_소구포인트_1",
  },
  {
    id: 21,
    광고채널: "KAKAOMOMENT",
    캠페인: "demo_설주윤_5_전환",
    광고세트: "demo_설주윤_5_전환_소구포인트_1",
    광고: "설주윤_화사한 수분크림 50ml_KAKAOMOMENT_1",
    이미지: "https://i.ibb.co/bg9Rhcv/no-image.png",
    제품명: null,
    광고비: "11,432원",
    전환수: "0",
    전환값: "0원",
    CPM: "0원",
    CTR: "0%",
    CPC: "0원",
    CPA: "0원",
    ROAS: "0%",
    ad_id: "demo_카페24화사한_화사한 수분크림 50ml_KAKAOMOMENT_18_1",
    ad_group_id: "demo_설주윤_5_전환_소구포인트_1",
  },
];
